#:schema https://json.schemastore.org/pyproject.json

[build-system]
requires = ["setuptools", "wheel", "torch==2.5.1", "ninja", "psutil", "packaging"]


[project]
name = "train"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "accelerate",
    "bitsandbytes",
    "datasets",
    "deepspeed",
    "einops",
    "isort",
    "jsonlines",
    "loralib",
    "vllm",
    "optimum",
    "packaging",
    "peft",
    "ray",
    "tensorboard",
    "torch==2.5.1",
    "torchmetrics",
    "tqdm",
    "transformers",
    "transformers_stream_generator",
    "wandb",
    "latex2sympy2",
    "timeout-decorator",
    "word2number",
    "wheel",
    "flash-attn",
]

[tool.uv]
no-build-isolation-package = ["flash-attn"]

[tool.setuptools]
packages = ["openrlhf"]

[tool.ruff.lint]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "PT",  # flake8-pytest-style
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
]
ignore = [
    "A003",   # builtin-attribute-shadowing
    "SIM108", # Use the ternary operator
    "UP007",  # Allow Optional[type] instead of X | Y
]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.pyright]
typeCheckingMode = "standard"